AWSTemplateFormatVersion: '2010-09-09'
Description: Simple S3 bucket with encryption, versioning and public access block
Resources:
  IacS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      Name: test-petnan
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  BucketName:
    Description: Name of the created bucket
   
