name: Deploy CloudFormation S3

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:  
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env


      - name: Install CloudFormation Guard
        run: |
          source $HOME/.cargo/env
          cargo install cfn-guard
          cfn-guard --version


      - name: Validate CloudFormation template
        run: |
          cfn-guard validate --rules s3-encryption.guard --data s3.yml

  deploy-dev:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials (from secrets)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
    
      - name: Deploy CloudFormation stack (S3)
        run: |
          aws cloudformation deploy \
            --template-file s3.yml \
            --stack-name iac-s3-bucket \
            --no-fail-on-empty-changeset
      

